### ISSUE TITLE
potential error in retrieving data from circular buffer

### ISSUE THREAD

**Issue by vstadnytskyi** [vstadnytskyi/icarus-nmr#15]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/femto-13/All-Projects-on-femto/LaserLab/Software/libraries/icarus-nmr/icarus_nmr/event_handler.py", line 514, in run
    self.run_once()
  File "/Users/femto-13/All-Projects-on-femto/LaserLab/Software/libraries/icarus-nmr/icarus_nmr/event_handler.py", line 538, in run_once
    self.evaluate_events()
  File "/Users/femto-13/All-Projects-on-femto/LaserLab/Software/libraries/icarus-nmr/icarus_nmr/event_handler.py", line 1243, in evaluate_events
    self.push_target_pressure()
  File "/Users/femto-13/All-Projects-on-femto/LaserLab/Software/libraries/icarus-nmr/icarus_nmr/event_handler.py", line 1371, in push_target_pressure
    target_pressure = scipy.stats.mode(data[:,0])[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by vstadnytskyi** [comment]
There is some problem in retrieving data from circular buffer when the global_pointer crosses the length of the circular buffer. 

```
input: N= 3 ; pointer = 101305 )
ERROR:root:Traceback (most recent call last):
  File "/Users/femto-13/All-Projects-on-femto/LaserLab/Software/libraries/icarus-nmr/icarus_nmr/event_handler.py", line 1815, in analyse_pump_event
    grad = gradient(target)
  File "<__array_function__ internals>", line 6, in gradient
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/function_base.py", line 1048, in gradient
    "Shape of array too small to calculate a numerical gradient, "
ValueError: Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.
```

**Comment by vstadnytskyi** [comment]
There were other issued that seemed to fix all of issues mentioned here
